### ISSUE TITLE
Tweet Sentiment Prebuilt Model

### ISSUE THREAD

**Issue by husnusensoy** [GlobalMaksimum/sadedegel#100]
Can somebody use sadedeGel to create a supervised classifier for any text classification problem in Turkish.

**Comment by husnusensoy** [comment]
This can be added into repository as a binder notebook

**Comment by askarbozcan** [comment]
Do you have any datasets in mind?
I found this: https://github.com/sercankulcu/twitterdata

**Comment by husnusensoy** [comment]
Whatever. We are  not addressing to apply to a single problem. Let's do several applications and publish our best results per problem. I keep this open and open two more tickets.

**Comment by husnusensoy** [comment]
@askarbozcan  can you explain the issue you have on tfidf ?
_"Will implement it with tfidf vectors as soon as other issues are fixed."_

**Comment by askarbozcan** [comment]
> @askarbozcan can you explain the issue you have on tfidf ?
I meant as soon as other PRs related to tfidf get merged into develop.

**Comment by husnusensoy** [comment]
I think you don't need to wait for it. Implement with the as is capabilities and ensure that results are reproducible. Once we have updated things we can rerun to obtain new results.

**Comment by husnusensoy** [comment]
@askarbozcan can you come up with a prebuilt model similar to sadedegel.prebuilt.news_classifier for twitter sentiment analysis.

**Comment by husnusensoy** [comment]
Obviously you can **properly** package `notebook/Basic Tweet Classification with Sadedegel.ipynb`
