### ISSUE TITLE
JSON Decode Error with Vocabulary Load

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#101]
Tests fail with new feature. Cannot load vocabulary json file due to decoding issues.

<img width="1111" alt="Screen Shot 2020-09-30 at 18 17 49" src="https://user-images.githubusercontent.com/25409216/94705315-927b9280-0349-11eb-9eb8-0add6d8875eb.png">

**Comment by husnusensoy** [comment]
Can you sen the exact code block you are calling to let us reproduce the case.

**Comment by dafajon** [comment]
Issue is not environment specific but due to lfs. Pulling again resolves [#101] 

<img width="562" alt="Screen Shot 2020-09-30 at 22 18 55" src="https://user-images.githubusercontent.com/25409216/94729834-f793b000-036a-11eb-9e5f-f4ec5e9ce18a.png">
