### ISSUE TITLE
Reduce coupling with configs?

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#104]
As of now with the example of  the only config so far, "word_tokenizer" config, the word_tokenizer is explicity set for Sentences class when set_config is called. However I believe it will complicate code further down the line when more configs are added.
I think modules reading configuration and setting their settings based on config instead of config script itself making the necessary changes would be better.

**Comment by husnusensoy** [comment]
You are completely right @askarbozcan. Current config is a complete mass which doesn't make me happy neither. With new idf and tfidf settings I will be refactoring it significantly by preserving the existing form for backward compatbility

**Comment by dafajon** [comment]
I agree. Current `WordTokenizer` gets its default value not from config but from its factory method. I think value checks should also be done in `config`. Can we agree that future config will:
- Supply user defined or default configurations to necessary classes.
- Check `config_name` and  its `value` when a new one is set by user.

**Comment by husnusensoy** [comment]
These issues are majorly resolved with release 0.16 (please refer to release notes) If we need more let's follow it up over new issues.
