### ISSUE TITLE
Disambiguate word tokenizer and sentence tokenizer

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#105]
As of now in code both word tokenizers and sentence tokenizers are simply called "tokenizer". Although it doesn't cause any technical problems as both are used in different contexts, calling word tokenizers "word_tokenizer" everywhere would bring more clarity and reduce mental load when reading the code.

**Comment by husnusensoy** [comment]
Actually the other way around. In general `tokenizer` refers to `word tokenizer` in NLP. `Sentence Tokenizer` refers to `sentence boundary detector`. We might update `sentence tokenizers` as `sbd` and `word tokenizers` to `tokenizer`. But note not to brake code by any means. We need to ensure backward compatibility.

You can send `hotfix` or `feature` fixing those.
