### ISSUE TITLE
Dynamic list of word_tokenizer choices for bblock.__main__

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#106]
Currently the choice of word tokenizer for vocabulary building is a fixed list where user has to choose which word tokenizer to use. Thus, if a new word tokenizer is added CLI interface isn't aware of it.

**Comment by husnusensoy** [comment]
Only tokenizers available in sadedegel can be used for that purpose ? What is the issue ?

**Comment by askarbozcan** [comment]
What I mean is, in bblock.main where options for vocabulary building are set 
`@click.option('--word-tokenizer', type=click.Choice(['bert', 'simple'], case_sensitive=False)`

tokenizers list is static. So if we add a new tokenizer, we will need to update this choice list every time.
It's almost a non-issue, but was worth pointing it out.

**Comment by husnusensoy** [comment]
This seems not to be an issue as we have discussed.
