### ISSUE TITLE
wandb integration

### ISSUE THREAD

**Issue by husnusensoy** [GlobalMaksimum/sadedegel#107]
Instead of publishing results in markdowns we can use **wandb**. Requires elaboration...

**Comment by dafajon** [comment]
I worked with W&B before for hyperparameter optimization. I can work on it. What is the specific format you suggest? The chart used for `hyperparameter sweeps`? 

<img width="626" alt="Screen Shot 2020-10-05 at 12 56 59" src="https://user-images.githubusercontent.com/25409216/95065888-501bd200-070a-11eb-9f71-82cca801b222.png">

**Comment by dafajon** [comment]
I want to assign this issue to myself and remove lowprio tag. Experiment amount and respective sized are getting bigger. We need **logging** at the least and **hyperparameter sweeps** for wide search spaces. I will start with first and extend on latter.

**Comment by dafajon** [comment]
I showed a demo on wand results publishing for the summarizers. The dashboard provided good visualization but it was decided it did not add much and still very cluttered.
