### ISSUE TITLE
Sequence magic methods for Doc object

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#111]
Implement indexing for Doc object, allowing user to pick specific Sentences object like this:
`doc[i]`

Although equivalent to `doc.sents[i]`, it's better if user won't have to use object's attributes manually.

UPD: Also add ability to iterate over Doc object just like any sequence.

**Comment by husnusensoy** [comment]
That will be great. Please do implement

`__getitem__` and `__iter__` functions as you explained on `Doc` object with proper test cases.

Regards,

**Comment by husnusensoy** [comment]
Resolved with commit dedb6332496daebf815656aea10a54a2c0d15fe1
