### ISSUE TITLE
Implement a Classifier

### ISSUE THREAD

**Issue by husnusensoy** [GlobalMaksimum/sadedegel#114]
UPD: Another (better) candidate: https://coltekin.github.io/offensive-turkish/

**Comment by dafajon** [comment]
Just like many packages libraries I suggest an `examples` directory for use cases of SadedeGel.

**Comment by askarbozcan** [comment]
> Just like many packages libraries I suggest an `examples` directory for use cases of SadedeGel to display such implementations.

Agreed. Also will allow us to add links to binder notebook on the examples/README.md for easy access.

**Comment by dafajon** [comment]
Here is a benchmark dataset for this task.

https://www.kaggle.com/savasy/ttc4900

**Comment by husnusensoy** [comment]
What is the next action for this task to be closed ?

**Comment by askarbozcan** [comment]
> What is the next action for this task to be closed ?
Upload our notebooks to /notebooks ?

**Comment by husnusensoy** [comment]
Pull request is sent ?

**Comment by askarbozcan** [comment]
#174 done :)

**Comment by dafajon** [comment]
I implemented a base class under `sadedegel.classification`. The PR is branched from `feature/tokenizer_data` named as `feature/news_classification`. The next action will be a training CLI that consumes the labeled dataset of TS Corpus.

**Comment by husnusensoy** [comment]
Let's track diffrent things in different issues. I will accept @askarbozcan 's pull request but this is not what we want. We need to show sadedegel can yield accuracyt results for different problem sets. Moreover this should be test across major releases. This might be related to what @dafajon has done.

**Comment by husnusensoy** [comment]
It seems that we are pretty done with this.
