### ISSUE TITLE
One config_context to rule them all.

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#120]
After new enhancements with `tf` and `idf` configs, there will be more than one option. Single `config_context` will do the job to temporarily change configurations.

```python
configs = {"word_tokenizer": "simple",
           "tf" : "log_norm",
           "idf" : "probabilistic"}

with config_context(**configs):
   ##RunSummarizer
   ...


```

**Comment by husnusensoy** [comment]
We indeed have this now which I will be documenting soon.
