### ISSUE TITLE
AttributeError: 'Token' object has no attribute 'id': Failing for OOV token?

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#126]
While trying to get tfidf embeddings, I got an error that Token object created has no id.
After investigation the token it failed on is OOV.
Since id property is retrieved from vocabulary, it seems that idf calculation (and tf for that matter) does not account for token being OOV.

Possible fix: Ignore OOV token in calculations?

**Comment by husnusensoy** [comment]
This is not a general issue. Can you immediately send a sampe document for us to reproduce the issue. Please use a proper document which we also need to include into unit tests...

**Comment by husnusensoy** [comment]
Can you download 0.15.2 and retest please.

**Comment by askarbozcan** [comment]
Yes, tested on 0.15.2.1 downloaded from pip:


```python
~/miniconda3/envs/geo/lib/python3.8/site-packages/sadedegel/bblock/doc.py in tf(self)
    207     @property
    208     def tf(self):
--> 209         v = np.zeros(len(Token.vocabulary))
    210 
    211         for token in self.tokens:

TypeError: object of type 'NoneType' has no len()
```

Not sure why it's not loading the vocabulary, but I'll look into it.

**Comment by husnusensoy** [comment]
Please DO UPLOAD the code snippet for us to reproduce the case.

**Comment by husnusensoy** [comment]
I did :(((

**Comment by askarbozcan** [comment]
Oh yeah, sorry.
The code causing it is when tfidf_embeddings is accessed:
```python
tweet_0 = Doc(df.iloc[103]["text"])
tfidf_embedding_0 = tweet_0.tfidf_embeddings
```

**Comment by husnusensoy** [comment]
@askarbozcan as a remedy can you manually instantiate your code with to see any further issues...

```python
from sadedegel.bblock import BertTokenizer
Token.set_vocabulary(BertTokenizer)
```

I will release a fix in the afternoon...

**Comment by husnusensoy** [comment]
Please update sadedegel 0.15.2.2 fix

**Comment by askarbozcan** [comment]
It's all working now :+1: 
I think this issue can be closed.
