### ISSUE TITLE
Recompute existing tokens on Tokenizer change

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#135]
As title says, if tokens have been generated and tokenizer changed, tokens stored in Sentences does not change.

**Comment by dafajon** [comment]
If user reinitializes their Doc object after tokenizer change, stored tokens should change. By this issue do you mean any of the currently initialized Sentences object(s) should receive an automatic update after tokenizer change?

**Comment by askarbozcan** [comment]
Yes

**Comment by dafajon** [comment]
How are you going to detect an initialized object? When the user tries to access any of its properties?

**Comment by askarbozcan** [comment]
Sure, by modifying the `token` getter.
Just need to store which tokenizer was used to compute tokens used by Sentences object.

**Comment by husnusensoy** [comment]
Check the pull request comment. Open this after next release if we still need this.
