### ISSUE TITLE
Document Level Bert Embedding

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#137]
Implement doc level Bert embeddings. Mean of token embeddings are used to obtain sentence embeddings. For Doc-Bert embeddings:

- [x] Mean of Sentence embeddings.

- [x] Weighted mean of sentece embeddings (Rouge1 Scores as weights.)

- [x] Weighted mean of sentence embeddings (Length as weights.)

- [ ] Feed full document as a sequence to Bert. Keep in mind that max sequence length is 512. Can be addressed as a separate issue/PR.

**Comment by askarbozcan** [comment]
Another suggestion to deal with 512 token limit:
Feed document summarized with Rouge1 summarizer if the document does not fill fully.

**Comment by husnusensoy** [comment]
Duplicate of #170
