### ISSUE TITLE
Encode/Embed Functionality

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#138]
For users that just want to use embedding extraction  - without touching any other building blocks - for their texts at hand, add `encode` or `embed` function that takes **text**, desired **embedding type** (bert, w2vec, tfidf) and **level** (sentence, document) as a parameter and returns fixed length array(s) for the downstream task user wants.

**Comment by askarbozcan** [comment]
Related to that, I think it would be a nice idea to expose the functionalities of Sadedegel as procedural interface, though that might require a bit of an architecture change.

**Comment by husnusensoy** [comment]
Waiting for the pull request as we have talked.

**Comment by dafajon** [comment]
This functionality is provided by `extensions.sklearn`. No need for and extra endpoint for embedding generation.
