### ISSUE TITLE
seq2seq text normalization

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#143]
I propose a seq2seq based character level text normalization model.

Assuming Wikipedia corpus has more or less formal, grammatically correct language a seq2seq model can be trained by perturbing source text with various techniques (elongating vowels, changing ş -> s, etc, randomly adding/removing letters) and reconstructing the original error-free text.

**Comment by husnusensoy** [comment]
Can we also check [`Simpler Auto Corrector`](https://github.com/fsondej/autocorrect)

**Comment by askarbozcan** [comment]
Char-level models did not train/work properly.
Closed until a good, efficient solution is found.
