### ISSUE TITLE
Token objects instead of strings in Sentence

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#144]
Given a `Sentences` instance `s`, return `List[Token]` when `s.tokens` is called.

**Comment by askarbozcan** [comment]
+1.
Will be also quite useful when we add POS, NER and a morphological analyzer.

**Comment by husnusensoy** [comment]
We will be removing `sents` on `Doc` by `0.17` (we have already deprecated as you know) how about using __iter__ and __getitem__ on Sentence. So that followings will make sense ?

```python
s # s is an instance of Sentence

s[i]
```

```python
s # s is an instance of Sentence

for token in s:
    ...
```

```python
s # s is an instance of Sentence

tokens = list(s)
```

**Comment by askarbozcan** [comment]
Makes sense, will also be consistent with the way Sentences are accessed.

**Comment by dafajon** [comment]
Will do the work simpler.

**Comment by husnusensoy** [comment]
can one of you send the required pull request. Sad to say but I have
noticed that majority the test cases just test happy paths ensure that you
properly implement the required unit tests  per feature...

Hüsnü Şensoy / VLDB Expert
husnu.sensoy@globalmaksimum.com

[image: Global Maksimum Data & Information Tech]

Global Maksimum Data & Information Tech
+902162506637 / +902162506600
Acıbadem Mah. Çeçen Sk. Akasya Kule A-3
No:25 Kat:14 34660 Üsküdar, İstanbul Türkiye

[image: LinkedIn] <https://htmlsig.com/t/0000001BRGEK6> [image: Instagram]
<https://htmlsig.com/t/000001DZYDYM> [image: Github]
<https://htmlsig.com/t/000001DDAY0N>

**Comment by dafajon** [comment]
Sure.
