### ISSUE TITLE
Build a classification model with Tokenization corpus.

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#145]
Tokenization corpus contains 302936 news documents with category labels. 

- Examine categories.
- Fix an evaluation set with stratified sampling.
- Decide metric/loss. 
- Train a supervised news categorization model with document level embeddings:

- [ ] `bert_embeddings`

- [ ]  `tfidf_embeddings`

- [ ] Extend to `fasttext` upon arrival.

**Comment by husnusensoy** [comment]
@dafajon can someone proceed on this.

**Comment by dafajon** [comment]
This is already implemented as our pre-built news classifier. Tokenization corpus was later on renamed as `tscorpus`.

**Comment by dafajon** [comment]
Is there anything specific over that, that we can proceed?

**Comment by husnusensoy** [comment]
We now have w2v embeddings per token type. Maybe you can try to combine tfidf with w2v (avg/max/min/sum) to come up a better classifier ?

**Comment by dafajon** [comment]
Yes of course. That is what I had in mind, after reading my original comment.
