### ISSUE TITLE
pip Installer Uninstalls Newer Versions of Required Packages

### ISSUE THREAD

**Issue by ertugrul-dmr** [GlobalMaksimum/sadedegel#153]
![Screenshot_2020-10-23 Classification Using SadedeGel(1)](https://user-images.githubusercontent.com/61366446/97006242-3e2e9180-1548-11eb-98cc-5a12ae5b37dc.png)

As seen in screenshot above, installing sadedegel package on updated environments making some packages to get uninstalled and downgraded. Takes long time to download bigger packages like torch...

**Comment by husnusensoy** [comment]
You are right. But this is more than a sadedegel issue. Current number of contributors does not allow us to extensively test library with different versions of each dependency. On the other hand we need to ensure stability of the library wrt dependencies

What I can recommend

1. Use separate environment using your python package manager
2. Use `pip install --no-deps sadegel` if you are sure that higher versions in your environment will not cause an issue.
