### ISSUE TITLE
Store OOV Tokens of a Sentence instance.

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#154]
When user calls `bert`,`tfidf`, `word2vec`, `fasttext` or any other embedding, the generation relies on:

1. Selected tokenizer.
2. Selected preprocessing. (`bert` has hashtags, `word2vec` lowerizes etc.)
3. Vocab built on that tokenizer and preprocessing.

So when any of the embeddings are used,  a `sentence._oov` attribute should return
```python 
{'word2vec_bert': List[str], 
'tfidf_simple': List[str], ...} 
```

for used embeddings. This way user or developers can use oov tokens in their performance analysis for NLP tasks that use any of these embeddings.

**Comment by husnusensoy** [comment]
There is a `is_oov` flag already on Token object. Do u need something more than that ?

**Comment by dafajon** [comment]
Token having that flag will satisfy the need when Sentences object contain Token objects. This proposal would be a temporary solution until then and redundant after. 

Still after that, the user will need to parse all Tokens to collect and see all oov's of a sentence or a document.

**Comment by husnusensoy** [comment]
Can you check the code ? It's already there...
Hüsnü Şensoy / VLDB Expert
husnu.sensoy@globalmaksimum.com

[image: Global Maksimum Data & Information Tech]

Global Maksimum Data & Information Tech
+902162506637 / +902162506600
Acıbadem Mah. Çeçen Sk. Akasya Kule A-3
No:25 Kat:14 34660 Üsküdar, İstanbul Türkiye

[image: LinkedIn] <https://htmlsig.com/t/0000001BRGEK6> [image: Instagram]
<https://htmlsig.com/t/000001DZYDYM> [image: Github]
<https://htmlsig.com/t/000001DDAY0N>
