### ISSUE TITLE
Broken vocabulary creation

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#156]
When building vocabulary (by calling bblock.__main__, RAM usage shoots up and consumes all memory, forcing me to close down vocabulary creation.

It happens after all the documents are loaded and saving is about to happen.

After investigating the underlying issue it seems that the problem is conversion of Entry dataclass into dict. More specifically Entry dataclass contains reference to its Vocabulary as a property which I think creates a problem because it copies the Vocabulary object somewhere, causing an explosion of usage in memory.

I propose removing the reference to Vocabulary object in the Entry dataclass entirely and adapting the code where the entry's reference to its vocabulary is used (which seems to be two idf methods in token.py) OR creating a custom class (not dataclass) which wouldn't return dictionary with the reference to the vocabulary.

**Comment by husnusensoy** [comment]
Is this for development branch ?
Hüsnü Şensoy / VLDB Expert
husnu.sensoy@globalmaksimum.com

[image: Global Maksimum Data & Information Tech]

Global Maksimum Data & Information Tech
+902162506637 / +902162506600
Acıbadem Mah. Çeçen Sk. Akasya Kule A-3
No:25 Kat:14 34660 Üsküdar, İstanbul Türkiye

[image: LinkedIn] <https://htmlsig.com/t/0000001BRGEK6> [image: Instagram]
<https://htmlsig.com/t/000001DZYDYM> [image: Github]
<https://htmlsig.com/t/000001DDAY0N>

**Comment by askarbozcan** [comment]
Yes.

**Comment by husnusensoy** [comment]
Haven't tested yet but I will.
Hüsnü Şensoy / VLDB Expert
husnu.sensoy@globalmaksimum.com

[image: Global Maksimum Data & Information Tech]

Global Maksimum Data & Information Tech
+902162506637 / +902162506600
Acıbadem Mah. Çeçen Sk. Akasya Kule A-3
No:25 Kat:14 34660 Üsküdar, İstanbul Türkiye

[image: LinkedIn] <https://htmlsig.com/t/0000001BRGEK6> [image: Instagram]
<https://htmlsig.com/t/000001DZYDYM> [image: Github]
<https://htmlsig.com/t/000001DDAY0N>

**Comment by husnusensoy** [comment]
We now build 3 vocabularies without an issue.
