### ISSUE TITLE
Tokenizer does not change in latest develop

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#158]
<img width="538" alt="Screen Shot 2020-10-27 at 18 26 53" src="https://user-images.githubusercontent.com/25409216/97323710-23c72180-1882-11eb-92aa-8b64c18eb152.png">

<img width="546" alt="Screen Shot 2020-10-27 at 18 27 06" src="https://user-images.githubusercontent.com/25409216/97323705-2295f480-1882-11eb-9989-355e0804dc2d.png">

I added this case in test. In previous usage before new updates I had no trouble with setting `simple` I can verify that; but apparently current test cases were not enough to catch this in latest develop. I created some non-trivial cases fro tokenizers.

**Comment by dafajon** [comment]
Same case with current release on `PyPI`  

**Bert**
<img width="524" alt="Screen Shot 2020-10-27 at 18 45 06" src="https://user-images.githubusercontent.com/25409216/97325982-93d6a700-1884-11eb-8236-0855d4257eb0.png">
**Simple**
<img width="943" alt="Screen Shot 2020-10-27 at 18 44 42" src="https://user-images.githubusercontent.com/25409216/97325993-96390100-1884-11eb-9681-a3e35ae7c35c.png">

**Comment by husnusensoy** [comment]
This bug seems to be resolved by 5e0f92713a62f7adc63df79b534e09c35e664426
