### ISSUE TITLE
SBD Can't Handle Empty Sequences

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#169]
Some datasets may contain empty strings. Passing empty sequence to `Doc` throws error. An empty sequence should be detected and handled before it hits SBD.

<img width="738" alt="Screen Shot 2020-12-17 at 14 02 24" src="https://user-images.githubusercontent.com/25409216/102479891-8eb9fb00-4070-11eb-8bf2-2ab4cd6074f1.png">

**Comment by askarbozcan** [comment]
Just got this issue as well.
