### ISSUE TITLE
Relax dependencies

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#179]
Right now, all dependencies need the exact same version as written in requirements. However this makes Sadedegel hard to install via pip, especially due to torch==1.5.1 dependency.

Perhaps change strict equality to equal or greater?

**Comment by husnusensoy** [comment]
You are right. But until we reach a stable release we are reluctant to tackle with issues caused by dependency versions. Until then we strongly do recommend to use virtual environments whether you use pip or conda for package management.

**Comment by husnusensoy** [comment]
We have started that. Please do check `prod.requirements.txt` in version 0.19
