### ISSUE TITLE
Cannot change word tokenizer by set_config 

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#181]
Changing default value on `default.ini` and `tokenizer_context` works for changing tokenizer configuration. But there still seems to be an issue with `set_config`. @askarbozcan ran into same issue as well.

```python
In [1]: from sadedegel.config import set_config

In [2]: from sadedegel import Doc

In [3]: set_config("word_tokenizer", "simple")

In [4]: d = Doc("çekoslovakyalılaştıramadıklarmızdan mısnız?")
2021-01-05 15:25:40.621 | INFO     | sadedegel.ml.sbd:predict:22 - Loading sbd model from /Users/dorukhanafacan/sadedegel/sadedegel/ml/model/sbd.pickle

In [5]: d.tokens
Out[5]: 
['çek',
 '##os',
 '##lovak',
 '##yalı',
 '##laştır',
 '##amadı',
 '##k',
 '##larm',
 '##ızdan',
 'mıs',
 '##nı',
 '##z',
 '?']
```

**Comment by dafajon** [comment]
Replicated the case in both.

**Comment by husnusensoy** [comment]
Please provide proper details for us to resolve your cases. I believe this is a machine generated spam issue.
Closing ...

**Comment by husnusensoy** [comment]
- Please do provide commit ID on develop branch
- Specific version you have the issue

**Comment by dafajon** [comment]
Issue occurs in release `0.16.2` and develop branch c8b2262.

**Comment by husnusensoy** [comment]
We have reproduced the case and seems that some depreciated features haven't marked properly as so. Hotfix 0.16.2.1 will resolve the issue hopefully.

**Comment by husnusensoy** [comment]
Please try using 

```python
from sadedegel.config import config_context

with config_context(tokenizer="simple") as Doc:
  d = Doc("çekoslovakyalılaştıramadıklarmızdan mısnız?")
```

**Comment by husnusensoy** [comment]
Can u confirm that we have resolved this issue?

**Comment by dafajon** [comment]
Updated to `0.16.2.1` and also used develop at e0bda4c. I can confirm it is resolved. Thanks.

**Comment by husnusensoy** [comment]
e0bda4cf9198330ea2d7f36b5ecd3bc550f78fd5 resolves issue
