### ISSUE TITLE
Customer Satisfaction Prebuilt Model

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#192]
Build a sentiment classification model on `pos`, `neg`, `neutral` targets of customer product reviews. [Candidate Dataset](https://www.kaggle.com/burhanbilenn/duygu-analizi-icin-urun-yorumlari)

Other datasets have 5 star rating as targets. They can be binned into sentiments. Or a different prebuilt implementation can be discussed.

**Comment by husnusensoy** [comment]
PR is pending ?

**Comment by dafajon** [comment]
PR is rejected due to small dataset size. Also the model implementation is outdated given our current pre-built model standards.
