### ISSUE TITLE
Freq Tf needs smoothing to handle certain edge cases

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#193]
**Case**
For a pipeline with:
```python
 OnlinePipeline([
        ("tfidf", TfidfVectorizer(tf_method='freq', idf_method='smooth')),
        ("nb_model", MultinomialNB(alpha=1.0, fit_prior=True))
    ])
```
and ```TfIdfVectorizer```defaults as:
```python
 def __init__(self, *, tf_method='raw', idf_method='probabilistic', drop_stopwords=True, lowercase=True,
                 drop_suffix=True, drop_punct=True, show_progress=True):
```

Training and inference produces such error for `sklearn` models on develop 880b06f:

```
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
```

Replicating the error with a case:

```python
# Import saved model.
model = customer_sentiment.load()

# Pick a document from test set that produces error
model.predict(["ıyi"])

In [30]: ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
````

Went further to understand what get_tfidf in vectorizer produces:
```python 
In [31]: d = Doc('ıyi')

In [32]: d.get_tfidf(tf_method='freq', idf_method='smooth', drop_stopwords=True, lowercase=True, drop_suffix=True, drop_punct=True)
/Users/dorukhanafacan/sadedegel/sadedegel/bblock/doc.py:196: RuntimeWarning: invalid value encountered in true_divide
  drop_punct).sum())
Out[32]: array([nan, nan, nan, ..., nan, nan, nan])

```

**Proposal**
- Appearently removing tokens with certain properties leaves an empty document. Resulting division by zero for `raw_tf` calculation.
- I tried to add `epsilon=1e-3` to denominator and the problem did not occur in training and inference with all train and eval set respectively.
- I propose a hotfix by above solution. We encountered this when working on #191 and #192. We are done with the issues but wish to proceed after the hotfix and try `raw_tf` in our hyperparamter search.

**Comment by husnusensoy** [comment]
Cool catch. Let us check quickly!!!

**Comment by husnusensoy** [comment]
Bad luck :) Here is the issue

1.  **ıyi** word is tokenized into **ı, ##yi** by BERT tokenizer.
2. ı token is in the list of stopwords
3. ##yi token is a suffix.
As you exclude both tf vector (raw) turns out to be 0 vector. freq is raw / raw.sum() causing a division by zero in return nan

So the behaviour is correct and this is not a bug :)

**Comment by husnusensoy** [comment]
We can define this case a 0 vector by convention ?

**Comment by dafajon** [comment]
A default infinetsimal `epsilon` value added at the denominator would eliminate any possiblity of division by zero. This is a single stroke solution I can think of. Already worked a feature branch on it with tests. I can send PR now.

**Comment by dafajon** [comment]
It returns a zero vector.

**Comment by husnusensoy** [comment]
?

**Comment by husnusensoy** [comment]
We have the same potential issue for `double_norm_tf` also (which also includes division)

**Comment by dafajon** [comment]
Yes indeed. I covered that too.

**Comment by husnusensoy** [comment]
Please update your version to 0.17.1

**Comment by husnusensoy** [comment]
Can you confirm for the fix and close the issue if all fine ?

**Comment by husnusensoy** [comment]
@dafajon can you confirm ?

**Comment by dafajon** [comment]
I confirm. The issue is fixed on the case I reported.

**Comment by husnusensoy** [comment]
Thanx
