### ISSUE TITLE
Found duplicate functions in sadedegel.bblock.util

### ISSUE THREAD

**Issue by ertugrul-dmr** [GlobalMaksimum/sadedegel#208]
While checking `sadedegel.bblock.util.py` I found out `space_pad` function written twice. They look identical and removing one of them would fix the issue.

Here's the part:

```
def space_pad(token):
    return " " + token + " "


def space_pad(token):
    return " " + token + " "
```

**Comment by husnusensoy** [comment]
Closed with  #209
