### ISSUE TITLE
Add finetuning capabilities to BERT

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#210]
For many NLP tasks today big pretrained transformers are king.
However the current integration of Huggingface BERT into SG has a lot to be desired.
For these purposes these tasks will need to be done:

- [ ] Don't load Bert model directly in DocBuilder (use the wrapper class instead)
- [ ] Add finetuning/checkpointing capabilities to the BertWrapper code

Depends on #132 being merged

**Comment by dafajon** [comment]
This can be implemented easily now by integrating the training api of `transformers`.

**Comment by dafajon** [comment]
Private model zoo has the fine tuning capabilities. I don't think this should be open sourced as it will just wrap `huggingface` API. The real value is to host this sort of capability on a platform.
