### ISSUE TITLE
Make Pytorch an optional dependency

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#211]
Pytorch is a huge dependency and makes installing Sadedegel (even on a fresh environment) a chore, especially considering torch==1.5.1 dependency.
However in sadedegel the only place where Torch is used is for BERT embeddings. Make it an optional dependency, with pytorch import errors handled by BertWrapper (#132).

**Comment by husnusensoy** [comment]
We can sure do as we do `pandas` for prebuilt model training once we provide different embeddings into library.

**Comment by askarbozcan** [comment]
Switched from low priority to high priority because it makes it impossible to install Sadedegel in Colab-like enviornments.

**Comment by husnusensoy** [comment]
Can you elaborate more on this ? What is the case ?
Hüsnü Şensoy / VLDB Expert
husnu.sensoy@globalmaksimum.com

[image: Global Maksimum Data & Information Tech]

Global Maksimum Data & Information Tech
+902162506637 / +902162506600
Acıbadem Mah. Çeçen Sk. Akasya Kule A-3
No:25 Kat:14 34660 Üsküdar, İstanbul Türkiye

[image: LinkedIn] <https://htmlsig.com/t/0000001BRGEK6> [image: Instagram]
<https://htmlsig.com/t/000001DZYDYM> [image: Github]
<https://htmlsig.com/t/000001DDAY0N>

**Comment by askarbozcan** [comment]
My bad. I checked again in a clean colab notebook.
I have mixed up #215 with torch==1.5.1 installation.

**Comment by husnusensoy** [comment]
Can we close the issue if we are done?

**Comment by askarbozcan** [comment]
I believe this issue should still stay up as Torch is a really big dependency despite only being used for BERT-related stuff.
So making it optional would still be beneficial.

**Comment by husnusensoy** [comment]
I agree.  To clarify what you propose is if you use BERT import torch etc other wise no need.

**Comment by husnusensoy** [comment]
Bert is now an optional component which can be insalled using `pip install sadedegel[bert]`
