### ISSUE TITLE
pip install does not work in Colab

### ISSUE THREAD

**Issue by demegire** [GlobalMaksimum/sadedegel#215]
Running "!pip install sadedegel" exits with the following error:
"ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output."

This was not the case 1 week ago and the library could be installed with no problem. 

To reproduce:
Open a Google Colab notebook and run:
!pip install sadedegel

**Comment by ertugrul-dmr** [comment]
Thanks for reporting the issue, I think that's related to recent update with `uvloop` package. I think you can temporarily  fix the issue by entering `!pip install uvloop==0.14.0` in colab before you install sadedegel, until it's fixed...
