### ISSUE TITLE
Related to Telco Sentiment Model

### ISSUE THREAD

**Issue by husnusensoy** [GlobalMaksimum/sadedegel#247]
*    Link you mentioned in documentattion (README) states ...open source [benchmark](https://ieeexplore.ieee.org/document/8554037/)... Paper is not open and requires IEEE authentication. Do I miss something ?
 *  Let's discuss whether we will host benchmark passing model here or not. I think you mean sadedegel private model ? What is you current model accuracy ?

Pull request #246

**Comment by dafajon** [comment]
- There is no online open link. I have the paper I will send in private.
- Yes I mean private model. I ran a new optimization lets discuss accuracy after the update.

**Comment by dafajon** [comment]
Since the dataset and prebuilt model are implemented and merged I am closing this issue. Further TODO are:
- Error analysis (currently working on)
- Feature ideas for improvement.
- Improved private model.
