### ISSUE TITLE
Id-Token Mapping for TfIdf

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#261]
- We need an easy access to Id-Token mappings in a vocabulary to see  which token an index of a TfIdf vector refers to.

**Comment by husnusensoy** [comment]
Completely legitimate request :) development branch now includes following features on `Vocabulary` class 

- `id_to_feature`
- `feature_to_id`
- `id_to_feature_cs`
- `feature_cs_to_id`

**Comment by dafajon** [comment]
Resolved in 57436ca.

**Comment by dafajon** [comment]
Resolved in 57436ca.
