### ISSUE TITLE
Re-Evaluate Open Source Movie Sentiment Model

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#284]
Re-evaluate current model and write results to README.md

**Comment by ertugrul-dmr** [comment]
![image](https://user-images.githubusercontent.com/61366446/125455341-0aadb6d7-d3f0-41c3-b8cc-ff07f623bec1.png)

These are the public model classification report I have under my hand. But I'll be testing it from scratch to double check soon.

**Comment by dafajon** [comment]
Please evaluate again and update README accordingly along with your private model report.
