### ISSUE TITLE
Create Example Usage Notebooks

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#311]
- Now that there is a new release, create use case notebooks on Google Colab and link it to the repository with a "colab" badge.

**Comment by husnusensoy** [comment]
That would be great.
Hüsnü Şensoy / VLDB Expert
***@***.***

[image: Global Maksimum Data & Information Tech]

Global Maksimum Data & Information Tech
+902162506637 / +902162506600
Acıbadem Mah. Çeçen Sk. Akasya Kule A-3
No:25 Kat:14 34660 Üsküdar, İstanbul Türkiye

[image: LinkedIn] <https://htmlsig.com/t/0000001BRGEK6> [image: Instagram]
<https://htmlsig.com/t/000001DZYDYM> [image: Github]
<https://htmlsig.com/t/000001DDAY0N>

**Comment by dafajon** [comment]
Deadline for this contrib is 17.02. Tasks are assigned.

**Comment by husnusensoy** [comment]
Ne oldu bu konu. Deadline varmis ?
Hüsnü Şensoy / VLDB Expert
***@***.***

[image: Global Maksimum Data & Information Tech]

Global Maksimum Data & Information Tech
+902162506637 / +902162506600
Acıbadem Mah. Çeçen Sk. Akasya Kule A-3
No:25 Kat:14 34660 Üsküdar, İstanbul Türkiye

[image: LinkedIn] <https://htmlsig.com/t/0000001BRGEK6> [image: Instagram]
<https://htmlsig.com/t/000001DZYDYM> [image: Github]
<https://htmlsig.com/t/000001DDAY0N>

**Comment by dafajon** [comment]
Geldi notebooklar bugün toplantıda. Koyacağım.

**Comment by askarbozcan** [comment]
All notebooks and example usages will be on a separate repo after cleanup.
