### ISSUE TITLE
__call__ method for summarizers to return the summary based on predict()'s scores.

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#33]
After changes to the code base, there's no way to easily get a summary now.
Suggestion: Define a `__call__` method for summarizers (with a base Summarizer class?) which would use predict()'s scores and return summary.

**Comment by husnusensoy** [comment]
Yes for sure.
Please do implement one with test cases and send a pull request. A feww notes

1. Ensure that __call__ can take either a parameter of type `Doc` or `sents` member of a `Doc` instance (which is a list of `Sentences`
2. Second parameter for the __call__ is `k` defining the number of sentences to be returned. 

return value is `List[Sentences]` (a slice of original `Doc.sents`)
