### ISSUE TITLE
Suspicious scores in annotated corpus

### ISSUE THREAD

**Issue by husnusensoy** [GlobalMaksimum/sadedegel#37]
I felt suspicious on the annotated corpus scores (`deletedInRound`). Please double check to ensure. Note that all our final evaluation of summarizer will be based on that.

**Comment by husnusensoy** [comment]
@dafajon @askarbozcan are you done with this with being sync ?

**Comment by dafajon** [comment]
We are sync. Final fixes are in @askarbozcan's PR.

**Comment by husnusensoy** [comment]
Resolved with commit 90db90acba125f84fa2ff631d8f7efe4e1628198
