### ISSUE TITLE
NLPPipeline and Summarizer object not up to par with the rest of the code.

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#44]
Summarizer (core) object (in sadedgel/core.py) needs to be updated to use better defaults such as Rouge1 summarizer and SBD sentence tokenizer. **Documentation on the main README.md should be updated to reflect the changes**

As an alternative this can be scrapped entirely, instead relying on Doc + Summarizers.

As another note, #40 depends on this issue's outcome.

**Comment by husnusensoy** [comment]
Addressed to issue #40 and #45
