### ISSUE TITLE
Turkish Characters

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#5]
Turkish characters are unicode in dataset documents. We can continue sentence cleaning like this but will character issue be fixed?

**Comment by husnusensoy** [comment]
Can you provide an example ?

**Comment by askarbozcan** [comment]
"Çünkü faiz indiriminin riskleri de var." =>
 "\u00c7\u00fcnk\u00fc faiz indiriminin riskleri de var."

**Comment by mccakir** [comment]
Next version of news scraper application will provide utf-8 encoded text files.
