### ISSUE TITLE
ModuleNotFoundError: No module named 'sadedegel.tokenize'; 'sadedegel' is not a package

### ISSUE THREAD

**Issue by Oguzhanercan** [GlobalMaksimum/sadedegel#55]
![Adsız](https://user-images.githubusercontent.com/64038202/89686000-21e66580-d906-11ea-9ea9-594b97acef93.png)

pip install sadedegel işlemini uygulamama rağmen module not found hatası alıyorum. Ne yapabirim ?

**Comment by husnusensoy** [comment]
Kendi yarattigin `sadedegel.py` dosyasini `sadedegel_deneme.py` falan yapip dener misin ?

Ayni isimde oldugun icin onceligin var.

**Comment by Oguzhanercan** [comment]
Teşekkürler farketmemişim. 
Numpy ve HDF5 kütüphanelerinin hangi sürümleri yüklü olması gerekiyor onlarla ilgilide hata alıyorum.

**Comment by husnusensoy** [comment]
`sadedegel` i nasil kurdun milmiyorum ama `pip3 install sadedegel` dediginde dependecyleriyle kurulmasi lazim. Bos ortama son surumu kurdugumda bendeki manzara asagidaki gibi

```
boto==2.49.0
boto3==1.14.37
botocore==1.17.37
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
docutils==0.15.2
fastapi==0.60.1
filelock==3.0.12
future==0.18.2
h11==0.9.0
httptools==0.1.1
idna==2.10
jmespath==0.10.0
joblib==0.16.0
loguru==0.5.1
nltk==3.5
numpy==1.19.1
packaging==20.4
pydantic==1.6.1
pyparsing==2.4.7
python-dateutil==2.8.1
regex==2020.7.14
requests==2.24.0
s3transfer==0.3.3
sacremoses==0.0.43
sadedegel==0.11.1
scikit-learn==0.23.2
scipy==1.5.2
sentencepiece==0.1.91
six==1.15.0
sklearn==0.0
smart-open==2.1.0
starlette==0.13.6
tabulate==0.8.7
threadpoolctl==2.1.0
tokenizers==0.8.1rc1
torch==1.5.1
tqdm==4.48.2
transformers==3.0.2
urllib3==1.25.10
uvicorn==0.11.8
uvloop==0.14.0
websockets==8.1
```

Tabi ki versiyondan vesiyona bu degisecektir. Bazi paketlerde ozellile security ile alakali bir seyler olursa guncelleme yapiliyor.

**Comment by Oguzhanercan** [comment]
Teşekkürler
