### ISSUE TITLE
Sentences are not in order

### ISSUE THREAD

**Issue by askarbozcan** [GlobalMaksimum/sadedegel#58]
It seems that the sentences output by extension are output in order of the score output by summarizer. However,  for more fluent text, top-k sentences should be output in their original order.

**Comment by husnusensoy** [comment]
@askarbozcan can you send us an example document for which sentence order is wrong. So that we can add this as a test case for service before the fix.

**Comment by askarbozcan** [comment]
A toy document:
`"aa aa aa. bb bb cc. aa bb."`

Last sentence has the highest score and would be displayed first without sorting.

**Comment by husnusensoy** [comment]
@askarbozcan  Can you spend some time to send a proper Turkish sentences which is also valid for human beings like us 😠 😡

**Comment by askarbozcan** [comment]
`"Ali Baba'nın bir çiftliği var. Çiftliğinde babanın koyunları var. 'Mee, mee' diye bağırır Ali babanın çiftliğinde."`
Same case, last sentence has higher score than the rest (checked with .predict() of Rouge1).

I thought the previous one would be good enough to test this bug :c

**Comment by husnusensoy** [comment]
We love you 💘  ❤️  😄
