### ISSUE TITLE
Elaborate on Word Tokenizer Accuracy Testing

### ISSUE THREAD

**Issue by husnusensoy** [GlobalMaksimum/sadedegel#65]

**Comment by husnusensoy** [comment]
- [ ] Literature survey for Turksish Corpus that can be used to measure word tokenizer accuracy

**Comment by dafajon** [comment]
* Add a `load_tokenized_corpus` for custom word tokenizer training and evaluation.
* Returns a dict/iterable with keys `sentences`:`List[str]`, `tokens`:`List[List[str]]`

**Comment by husnusensoy** [comment]
This is implementation detail. What i am asking is

- [ ] Where is the `raw corpus` file(s) ? (tarball etc)
- [ ] Where is the `tokenized corpus` file(s) ? (tarball etc)
- [ ] What exact format they are in etc.

**Comment by dafajon** [comment]
There is already a "raw_corpus". We should pick a different name w.r.t. word tokenization context such as:
* `raw_tokens_corpus`
* `processed_tokens_corpus`

They can be placed under `dataset/tokens` such as `dataset/sents`.

Our angel contributor have supplied us recently only with `processed_tokens` of all documents in his corpus, in a single `.txt` file. I asked for the raw version as well.  

Apart from that the documents in the corpus are not separated and indexed by an `id`. They are dumped in a single `.txt`. I will re-iterate my request if necessary.

**Comment by husnusensoy** [comment]
Namespace seperation can be done at module level. Name **Dorukhan** but module name **Afacan**. So full qualified name will be `afacan.dorukhan`

Can you share a sample document and corresponding tokenized document as an example to let a better understanding ?

**Comment by dafajon** [comment]
The raw sample document is not provided yet, I pinged the contributor last time he said gathering the raw document would take time. Below is an excerpt from the sample tokenized document:

`Koca bir duvar taşıyordun yüreğinde kimsenin aşamayacağı , aşmaya cesaret bile edemeyeceği . 
Dışa karşı güçlüydü , ama içe , kendi yüreğine yıkılmak üzereydi . 
Anılarla örülmüş , acılarla harçlanmış bu duvara tırmanmak , onu aşabilmenin ilk şartıydı . 
Vazgeçmek kolaydı , ertelemek de . 
Ama tırmanmaya başlandı mı bitirilmeli ! `

Each token including punctuations are separated by single whitespace in the `tokenized` form of the document. Raw is yet to be provided. I reminded him as I said. Will share the updates.
