### ISSUE TITLE
Hotfix Checklist on `develop` branch CONTRIBUTING.md

### ISSUE THREAD

**Issue by dafajon** [GlobalMaksimum/sadedegel#74]
* Current Hotfix checklist assumes merge into master and develop can be done by users or developers other than the commit master. 
* Instead of finishing the hotfix branch - which will merge the branch to master and develop in their local repositories - people should follow the path of pushing and pull requesting.

**Comment by husnusensoy** [comment]
You are perfectly right. Gone fix the documentation in next release.
