### ISSUE TITLE
Other IDF implementations

### ISSUE THREAD

**Issue by husnusensoy** [GlobalMaksimum/sadedegel#94]
Currect TF in idf calculation is made using idf smooth

But there are lots of different definitions required to be implemented. Check [tfidf](https://en.wikipedia.org/wiki/Tf%E2%80%93idf) for details.

Note that this should be a part of sadedegel configuration.

**Comment by dafajon** [comment]
Can IDF calculations be implemented as abstract factory at a separate `.py` . Then initialized and used inside `Token` s `idf`property depending on `config`.
