### ISSUE TITLE
Vocabulary with tokenizer specification

### ISSUE THREAD

**Issue by husnusensoy** [GlobalMaksimum/sadedegel#97]
Current Vocabulary is generated only based on BERT word tokenizer. If the word tokenizer is set to be simple in sadedegel configurator all Vocabulary related capabilities are disabled (such as tfidf summarizer)

Word tokenizer dependent vocabulary loader is required.

**Comment by askarbozcan** [comment]
Since different word tokenizers will produce different vocabularies, is it OK to name vocabulary as such "<TokenizerName>_vocabulary.json" and loading based on that?

**Comment by husnusensoy** [comment]
I am suspicious that we might have other files per word tokenizer in the future. So why not using data/bert/vocabulary.json and data/simple/vocabulary ?

**Comment by husnusensoy** [comment]
Check vocabulary structure on 0.19
