### ISSUE TITLE
Token Attibutes on Token class

### ISSUE THREAD

**Issue by husnusensoy** [GlobalMaksimum/sadedegel#98]
`idf` of a token is a token attribute/feature. There are lots of them. Just to mention a few

- [x] **is_punct**: Whether the token is a punctuation
- [x] **shape**: Shape defined in SpaCy tokens (very powerful coarse feature)
- [x] **is_number**: Whether the token is some numeric value or not.

**Comment by dafajon** [comment]
I will implement `is_number` as `is_digit` to stay parallel to SpaCy. Also I checked the implementation of above attributes within SpaCy. They are dependent on a `Lexeme` object. I think we will have our own workaround for these attributes for now instead mimicking the implementation in such detail?

**Comment by husnusensoy** [comment]
Since we currently don't have a morphological parser/disambiguator etc. our base object is Token. So Token is Lexeme in our case. Please do proceed
